***1. Creating Arrays***

In [2]:
import numpy as np

# 1
arr1 = np.arange(10)
arr2 = np.arange(3, 31, 3)
arr3 = np.ones(10, dtype=int)

print(arr1)
print(arr2)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[ 3  6  9 12 15 18 21 24 27 30]
[1 1 1 1 1 1 1 1 1 1]


***2. 2D Arrays***

In [3]:
arr4 = np.full((2, 5), 5)
arr5 = np.arange(9).reshape(3, 3)

print(arr4)
print(arr5)


[[5 5 5 5 5]
 [5 5 5 5 5]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


***3. Generate 5 random array***

In [4]:
rand_int = np.random.randint(0, 10, 5)
print(rand_int)

[3 5 9 8 5]


***4. Generate 10 random floating-point***

In [5]:
rand_float = np.round(np.random.uniform(0, 10, 10), 2)
print(rand_float)

[5.13 9.85 7.63 2.04 9.2  0.79 0.85 3.92 5.26 8.3 ]


***5. Generate 2D array***

In [6]:
rand_2d = np.random.randint(0, 10, (3, 4))
print(rand_2d)

[[2 2 4 1]
 [2 0 8 4]
 [4 4 8 6]]


***6. Basic Operations***

In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


***7. Matrix Addition***

In [8]:
m1 = np.zeros((3,3), dtype=int)
m2 = np.ones((3,3), dtype=int)
m3 = np.full((3,3), 2)
m4 = np.random.randint(0, 10, (3,3))

result = m1 + m2 + m3 + m4
print(result)

[[ 9 12  3]
 [ 7  8  9]
 [ 9  9  6]]


***8. Slicing 1D***

In [9]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:6])

[2 3 4 5 6]


***9. Slicing 2D***

In [10]:
arr2d = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])

# a
print("a:", arr2d[1])

# b
print("b:", arr2d[:,2])

# c
print("c:", arr2d[:3, 1:3])

a: [5 6 7 8]
b: [ 3  7 11 15]
c: [[ 2  3]
 [ 6  7]
 [10 11]]


***10. Even Numbers***

In [11]:
arr = np.arange(1, 51)
print(arr[arr % 2 == 0])

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


***11. Conditional Rows***

In [12]:
arr = np.round(np.random.uniform(0, 10, (4,5)), 1)

result = arr[(arr[:,1] > 2.0) & (arr[:,2] < 5.0)]
print(result)

[[4.7 4.1 2.7 6.5 7.5]]


***12. Replace Condition***

In [13]:
arr = np.arange(1, 21)

mask = ((arr % 2 == 0) | (arr % 3 == 0)) & ~((arr % 2 == 0) & (arr % 3 == 0))
arr[mask] = -1

print(arr)

[ 1 -1 -1 -1  5  6  7 -1 -1 -1 11 12 13 -1 -1 -1 17 18 19 -1]


***13. Reshape 1D → 2D***

In [14]:
arr = np.arange(20)
arr2d = arr.reshape(5, 4)
print(arr2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


***14. Flatten 2D***

In [15]:
arr = np.arange(20).reshape(4,5)
flat = arr.flatten()
print(flat)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


***15. Sum & Mean***

In [16]:
arr = np.array([1,2,3,4,5])

print(arr.sum())
print(arr.mean())

15
3.0


***16. Sum of Second Column***

In [17]:
arr = np.arange(20).reshape(4,5)
print(arr[:,1].sum())

34


***17. Mean of First 3 Rows***

In [18]:
print(arr[:3].mean())

7.0


***18. Min per Row & Column***

In [19]:
print(arr.min(axis=1))  # rows
print(arr.min(axis=0))  # columns

[ 0  5 10 15]
[0 1 2 3 4]


***19. Remove Duplicates***

In [20]:
arr = np.array([1,2,2,3,4,4,5])
print(np.unique(arr))

[1 2 3 4 5]


***20. Sorting***

In [21]:
arr = np.random.randint(10, 21, 10)

print(np.sort(arr))          # ascending
print(np.sort(arr)[::-1])    # descending

[10 10 12 14 14 15 19 20 20 20]
[20 20 20 19 15 14 14 12 10 10]


***21. Merge Arrays***

In [22]:
a = np.array([1,2,3])
b = np.array([4,5,6])

merged = np.concatenate((a,b))
print(merged)

[1 2 3 4 5 6]


***22. Common Elements***

In [23]:
a = np.random.randint(10, 21, 10)
b = np.random.randint(10, 21, 10)

print(np.intersect1d(a, b))

[13 14 18]


***23. Remove Specific Numbers***

In [24]:
arr = np.random.randint(1, 11, 10)
result = arr[~np.isin(arr, [1,2,3,4])]
print(result)

[ 8  8  7  6  9 10  9]


***24. Index of Max***

In [25]:
arr = np.arange(0, 5.5, 0.5)
print(np.argmax(arr))

10


***25. First Even > 5***

In [26]:
arr = np.array([1,3,6,7,8,2])

indices = np.where((arr % 2 == 0) & (arr > 5))[0]
print(indices[0] if len(indices) > 0 else -1)

2


***26. Add New Column***

In [27]:
arr = np.random.randint(1, 10, (4,5))

new_col = (arr[:,1] * arr[:,2]).reshape(-1,1)
result = np.hstack((arr, new_col))

print(result)

[[ 8  7  7  9  4 49]
 [ 6  3  1  2  1  3]
 [ 9  7  1  7  4  7]
 [ 2  6  4  4  4 24]]
